version: '3.3'
services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    # ADD THIS LINE:
    user: root
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/mnt
    volumes:
      - "C:/data/label_studio_db:/label-studio/data"
      - "C:/data/audio_interview:/mnt/audio:ro"
    command: label-studio start