name: agri_transcribe
channels:
  - conda-forge
dependencies:
  - python=3.10           # Safe for WhisperX
  - ffmpeg                # Audio tools
  - psycopg2              # Database
  - pandas
  - jupyterlab
  - ipywidgets
  - jupyterlab_widgets
  - pip                   # We need pip for Step 2 not on conda